blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'
urlpatterns = [
     path('', views.home_page, name='home_page'),
]

my_site/urls.py
from django.urls import include, path 
from django.contrib import admin

urlpatterns = [ 
     path('', include('blog.urls')), 
     path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
     comment = models.CharField(max_length=180, null=True, blank=True)
     user = models.CharField(max_length=180, null=True, blank=True)

blog/views.py
from django.shortcuts import render
from . models import Comment
def home_page(request):
    if request.method == 'POST':
        our_comment = request.POST.get('comment')
        our_user = request.POST.get("username")
        comment_obj = Comment.objects.create(
            comment=our_comment,
            user=our_user
        )

        return render(request, 'blog/home_page.html', {'comment': comment_obj,})
    return render(request, 'blog/home_page.html')

blog/templates/blog/home_page.html
<!DOCTYPE html>
<html>
<head>
	<title>Welcome to Dina's page</title>
</head>
<body>


<h1>Hi my name is dina. Welcome</h1>

<img src="https://tse3-mm.cn.bing.net/th?id=OIP.Njds_or8OjS2PhCkCGVekQHaFY&p=0&o=5&pid=1.1">

<h2>A Chinese rapper named 鬼卞</h2>
<p>
	Have you ever heard of him?(there is a picture of him above~)
	Talk about the information that you know about 鬼卞!!!!!


</p>

<button>Like</button>
<form action="{% url 'blog:home_page' %}" method="POST">
{% csrf_token %}
	<input type="text" placeholder="type your username" name="username">
	<textarea placeholder="Say whatever u want!!!" name="comment"></textarea>
	<input type="submit" value="Go!!!" name="">
</form>

<h2>WoW</h2>
User {{comment.user}} says: {{comment.comment}}

</body>
</html>